# Generated by Django 5.0.1 on 2024-07-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='New Conversation', max_length=255),
        ),
    ]
